services:
  redis:
    image: redis:latest

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  nginx:
    image: nginx:latest
    configs:
      - source: my_config_2
        target: /etc/nginx/conf.d/default.conf

  worker:
    image: uffizzitest/worker:latest
    deploy:
      resources:
        limits:
          memory: 250M

  vote:
    image: uffizzitest/vote:latest

  result:
    image: uffizzitest/result:latest

x-uffizzi-ingress:
  service: nginx
  port: 8080
  
x-uffizzi-continuous_preview:
  delete_preview_after: 1h
  deploy_preview_when_image_tag_is_created: true
  delete_preview_when_image_tag_is_updated: true
  
configs:
  my_config_2:
    file: ./config2/vote2.conf
