services:
  webhooks_test_app:
    image: registry.uffizzi.com/v2/8aed3d1a-9e28-48c8-bcd8-61a40d825fa6/manifests/60d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

x-uffizzi-ingress:
  service: webhooks_test_app
  port: 80

x-uffizzi-continuous-preview:
  delete_preview_after: 1h
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
