services:
  hello-world:
    build:
      context: https://github.com/moklidia/HELLO-world-1
    environment:
      - TEST_ENV_1=123
      - TEST_ENV_2=123
      - URL=https://example.com?k=1&f=2
      - ENV=${RAILS_ENV}
x-uffizzi:
  ingress:
    service: hello-world
    port: 80
