services:
  hello-world:
    build:
      context: https://github.com/moklidia/hello-world:master
    deploy:
      resources:
        limits:
          memory: 100M

ingress:
  service: hello-world
  port: 80
