services:
  hello-world:
    build:
      context: https://github.com/moklidia/hello-world:master
      dockerfile: Dockerfile
      args:
        RAILS_ENV: development
        NAME: hello-world-test-args

ingress:
  service: hello-world
  port: 80
