services:
  hello-world:
    build: 
      context: https://github.com/moklidia/hello-world-1
      dockerfile: /Dockerfile
    secrets:
      - database_user
      - database_password
        
secrets:
  database_user:
    external: true         
    name: "DATABASE_USER"        
  database_password:
    external: true
    name: "DATABASE_PASSWORD"

x-uffizzi:
  ingress:
    service: hello-world
    port: 80
    
  continuous_preview:
    share_to_github: true
    delete_preview_after: 1h
    delete_preview_when_image_tag_is_updated: true
    deploy_preview_when_image_tag_is_created: true
    delete_preview_when_pull_request_is_closed: true
    deploy_preview_when_pull_request_is_opened: true
