services:
  postgres:
    image: postgres
    secrets:
      - postgres_user
      - postgres_password

secrets:
  postgres_user:
    name: POSTGRES_USER
  postgres_password:
    name: POSTGRES_PASSWORD

x-uffizzi-ingress:
  service: postgres
  port: 80
