definitions:
  environment: &env-var
    TEST_USER: postgres_test
    TEST_PASSWORD: postgres_test

services:
  redis:
    image: redis:non-existent
    environment: *env-var

  postgres:
    image: postgres:9.6
    environment: *env-var

  nginx:
    image: nginx:latest

  worker:
    image: uffizzi/example-voting-app-worker:master
    deploy:
      resources:
        limits:
          memory: 250M

  vote:
    image: uffizzi/example-voting-app-vote:master

  result:
    image: uffizzi/example-voting-app-result:master

x-uffizzi-ingress:
  service: nginx
  port: 8080
  
x-uffizzi-continuous_preview:
  deploy_preview_when_pull_request_is_opened: true
  delete_preview_when_pull_request_is_closed: true
  delete_preview_after: 2h
  share_to_github: true
  deploy_preview_when_image_tag_is_created: true
  delete_preview_when_image_tag_is_updated: true
